### ISSUE TITLE
error C2440: 'static_cast': cannot convert from 'CDirectPlayLobby *' to 'IDirectPlayLobby2 *'

### ISSUE THREAD

**Issue by gynt** [Sh0wdown/RedirectPlay#2]
I get an error here:
error C2440: 'static_cast': cannot convert from 'CDirectPlayLobby *' to 'IDirectPlayLobby2 *'

![image](https://github.com/Sh0wdown/RedirectPlay/assets/4720007/b248f71f-ef03-4127-9803-e196f60a23f6)

The issue is that dplobby.h doesn't define Lobby3 as inheriting from Lobby2. (3 and 2 both inherit from 1). How did you solve this?

**Comment by Sh0wdown** [comment]
Apparently I had edited my dplobby.h to inherit Lobby3 from Lobby2. Maybe this was an oversight on DX side, since it makes more sense otherwise and all other interfaces also inherit the previous version. The ReadMe has been adjusted.
